Compatibility with PHP 7.2
Kdyby/Wkhtmltopdf pull request #8
Opened 2017-12-06 08:07 UTC by aleswita

- remove dependency on Nette\Utils\Object
- add methods param and return type hints
- strict types
- Nette Coding Standard

**BC breaks**
- require PHP ^7.1
- require Nette 2.4 || 3.0

2017-12-06 08:20 UTC, enumag requested changes
The diff is all screwed up somehow. I'm guessing you accidently changed line endings or indentation. Fix that so that I can review your changes.

I mean I can review them with ?w=1 but then I can't comment on them...

Also use https://github.com/Kdyby/StrictObjects instead of Nette\SmartObject.

2017-12-06 08:20 UTC, enumag commented on composer.json
> +		"nette/utils": "~2.4.0 || ~3.0.0"
Use `^` instead of `~`.

2017-12-06 09:05 UTC, aleswita commented
@enumag I'm working on Windows, so I was change the newlines to Unix format, now difs looks good

2017-12-06 09:06 UTC, enumag commented
Add the kdyby strict-objects dependency to composer.json. Otherwise it looks good.

2017-12-06 09:11 UTC, aleswita commented
@enumag done

2017-12-06 09:13 UTC, enumag commented
Also I'm thinking about merging https://github.com/Kdyby/Wkhtmltopdf/pull/6 first since it has travis setup and other good things. Could you review that PR and comment there what do you think about it?

2017-12-06 09:24 UTC, aleswita commented
Seems good, so if PR#6 are ok, merge first and I will try resolved conflicts.

2017-12-06 10:14 UTC, enumag commented
#6 is merged now. Also if you could do the change suggested [here](https://github.com/Kdyby/Wkhtmltopdf/pull/6/files#r30045182) it would be great.

2017-12-07 10:28 UTC, aleswita commented
@enumag one question, I have no experience with **Kdyby/StrictObjects**, its posible to read private variable with public getter like as **Nette\SmartObject**?

2017-12-07 10:51 UTC, enumag commented
@aleswita I have no idea. Personally I never used neither Kdyby/StrictObjects nor Nette\SmartObject. I'd be ok with not using any such trait in Kdyby packages but it's probably better to keep it consistent.

2017-12-08 05:41 UTC, aleswita commented
@enumag seems done

2018-01-15 23:18 UTC, dada-amater commented
Will this be merged? It is our php7.2 upgrade blocker. Thank you.

2018-01-16 06:21 UTC, enumag commented
I was focusing on Kdyby/Doctrine so I kind of forgot about this one. I need to review it but yes I intend to merge it soon. Thanks for reminding me.

2018-01-16 18:01 UTC, enumag requested changes
Remove useless annotations like `@return void` and other cases where `@param` and `@return` just duplicate the method signature.

2018-02-09 15:04 UTC, dada-amater commented
Any update? And please make new release, in composer there is still old v0.1.

2018-03-05 12:36 UTC, solcik commented
@enumag Could you merge this one and I will remove useless annotations in another PR as you requested above?

2018-03-05 14:01 UTC, enumag commented
@solcik Ok. Thinking about it more I'm not completely sure if the annotations aren't required by the code checker. Better test that before you remove them everywhere.

2018-03-05 14:01 UTC, merged

2018-03-12 17:54 UTC, dada-amater commented
@enumag @solcik @aleswita Thank you!